version: '3.9' # optional since v1.27.0
services:
  docker-backend:
    environment:
                -
    build:
      context: .
      dockerfile: Dockerfile
    image: backend_prod:local
    ports:
      - '7200:7200'
    volumes:
      - .:/nodec-
    restart: always

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql1Ipw